name: MLOps K3s CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: shivaaye04/mlops-deployment-2:latest

  continuous-deployment:
    needs: continuous-integration
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to K3s on AWS EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/ubuntu/mlops-deployment-2
            git pull origin main

            sudo k3s kubectl apply -f deployment.yaml
            sudo k3s kubectl apply -f service.yaml
            sudo k3s kubectl rollout restart deployment/mlops-deployment